### ISSUE TITLE
No usar date_default_timezone_set() sino current_time()

### ISSUE THREAD

**Issue by gonzalesc** [culqi/culqi-woocommerce#10]
Quería entender el porque mis pedidos "**pendientes de pago**" no llegaban a cancelarse luego de un periodo de tiempo, y fue debido que el plugin Wocommerce Culqi tenía seteado date_default_timezone_set de forma predeterminada.

`date_default_timezone_set('America/Lima');`

Esto hacía que **Wordpress** calcule mal las fechas y por ende no me cancelaba los pedidos pendientes. Simplemente comenté esa función y todo volvió a la normalidad.

Sólo hay que poner el timezone a Lima en Settings>General

Fuente: https://vip.wordpress.com/documentation/vip-development-tips-tricks/use-current_time-not-date_default_timezone_set/

Saludos

**Comment by brayancruces** [comment]
Hola @gonzalesc, gracias por la sugerencia Dicha linea ha sido eliminada. 

¡Gracias! 💯
