### ISSUE TITLE
Problema al realizar un pago con el plugin culqi en woocommerce

### ISSUE THREAD

**Issue by sponce87** [culqi/culqi-woocommerce#14]
Buenas tardes,
Tengo las siguientes versiones:
wordpress 4.7.3
woocommerce 2.6.14
culqi woocommerce 2.1.1

A la hora de realizar un pago con culqi me da el siguiente error:

Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.

Fri Mar 24 17:03:16 PET 2017
There was an unexpected error (type=Internal Server Error, status=500).
401 Unauthorized

Saben ustedes a qué se debe este error?

Saludos!!!

**Comment by marti1125** [comment]
@sponce87 podrias darme mas informacion para poder replicar el proceso o si tienes algun screenshoot. Gracias!

**Comment by sponce87** [comment]
Hola,

Lamentablemente no guardé un pantallazo; pero te puedo tratar de detallar lo que hice:

Seleccioné un producto para comprar.

Llené mis datos (nombre, apellido, dirección, telefono, correo, pais, ciudad, provincia y código postal) para comprarlo como usuario NO REGISTRADO.

Finalmente le di clic a pagar y fue cuando debió cargar el formulario de culqi, pero salió el error que mencioné (es decir el fondo transparente y en lugar del formulario, el texto anterior).

Ahora he regresado a la versión que tenía antes de culqi (1.0.4) y no he tenido problema.

Muchas gracias por tu atención.

Saludos!!!

**Comment by sponce87** [comment]
Hola, 

He probado con la version 2.1.0 y me dio el mismo error, te adjunto el pantallazo.

Saludos!!!

![error_pago](https://cloud.githubusercontent.com/assets/26662010/24317480/71771ba6-10c5-11e7-921c-5b02fb3e4883.png)

**Comment by oswaldocfr** [comment]
@sponce87 Probaste actualizar al API v2 e ingresar las nuevas llaves?

**Comment by marti1125** [comment]
@sponce87 Alguna novedad se llevo a corregir el problema de las llave o el problema persiste =?

**Comment by sponce87** [comment]
Hola!,

Sí, efectivamente, era un problema con las llaves. Actualicé al API v2 y con las nuevas llaves salió la ventana de Culqi para realizar el pago.

Muchas gracias!!!
