### ISSUE TITLE
Problema si deseo usar el pago por Culqi como Pago Directo usando Recibos de WooCommerce

### ISSUE THREAD

**Issue by sparkheroe** [culqi/culqi-woocommerce#17]
Hola, si bien me funciona normal si es que agrego productos en mi carrito de compras de mi página. Cuando quiero hacer generar recibos (checkouts) y enviarles un link a mis clientes para que puedan hacer sus pagos, me aparece un mensaje diciéndome que no se puede finalizar la compra a menos que tenga algo en el carrito de compras. 

No estoy seguro si es una condición del mismo WooCommerce pero con otro plugin, si me logra hacer los pagos. 

![image](https://user-images.githubusercontent.com/28207796/28214946-da8d9814-6871-11e7-9109-95d312d42f5b.png)

Saludos y gracias.

**Comment by marti1125** [comment]
@LizRuelas creo ya has visto este tema antes =?

**Comment by LizRuelas** [comment]
Si ya lo vimos antes :/
Por el momento nuestro Plugin no contempla "links" para proporcionar al cliente.

**Comment by sparkheroe** [comment]
Ya veo, gracias por la rápida respuesta.

**Comment by sparkheroe** [comment]
Voy a ver si podemos acoplarlo de esa manera, si es así les alcanzo igual el código.
