### ISSUE TITLE
Pagos recurrentes Woocommerce

### ISSUE THREAD

**Issue by Meowperino** [culqi/culqi-woocommerce#19]
Tengo una pagina donde planeo vender libros que se puedan pagar en cuotas, como puedo habilitar esa opción. 

![photo_2017-08-02_00-23-41](https://user-images.githubusercontent.com/24441400/28857628-df02b202-7718-11e7-937b-cfe560e845a8.jpg)

**Comment by marti1125** [comment]
Hola @Meowperino para hacer pagos recurrentes tendrias que utilizar el api 
 https://www.culqi.com/api/#/suscripciones#create pero los puglins que tenemos solo crear cargo y el checkout detecta la cantidad de cuotas a pagar si es tarjeta de credito

**Comment by christianllv** [comment]
Hola @marti1125, tienen algún plan de lanzar el plugin con pagos recurrentes? Si es así, tienen un tiempo estimado? Gracias de antemano.

**Comment by paginasweb** [comment]
Hola Christian, que tal? no sabia que requerías este plugin, nosotros lo tenemos para woocomerce, si deseas te podemos vender el código, háblame por skype
