### ISSUE TITLE
Problema de compatibilidad del plugin con algunos themes

### ISSUE THREAD

**Issue by christianllv** [culqi/culqi-woocommerce#21]
En algunos themes, al pulsar sobre Comprar o Cancelar, no sucede nada.
Con el pull request enviado se soluciona esto.

Saludos

**Comment by skyblue314** [comment]
cual es el pull request?

**Comment by skyblue314** [comment]
yo tengo problema de compatibilidad

**Comment by LizRuelas** [comment]
Hola @skyblue314 escríbeme a liz.ruelas@culqi.com para pasarte el plugin compatible con algunos themes.

Saludos

**Comment by christianllv** [comment]
@LizRuelas y por que nunca aceptaron mi PR?

**Comment by jcvillacorta** [comment]
Tengo el mismo problema. Recién he instalado el plugin y no pasa nada al poner "pagar". La web es https://infomercado.pe/store
