### ISSUE TITLE
Insertar Página de redireccionamiento al completar el pago

### ISSUE THREAD

**Issue by kasbsquall** [culqi/culqi-woocommerce#23]
Buenas, eh estado intentando sin éxito hacer que cuando ya pasaste la parte de pago y te carga el texto de PAGO EXITOSO automáticamente te redireccione a una página de agradecimiento.
algo así como que te lleve a www.mipagina.com/gracias.

Como es posible hacer esto? me podrían brindar que lineas de código tendría que agregar y donde por favor.

**Comment by marti1125** [comment]
puedes usar https://developer.wordpress.org/reference/functions/wp_redirect/ 
en esta parte lo puedes agregar
https://github.com/culqi/culqi-woocommerce/blob/master/culqi-woocommerce.php#L455

**Comment by marti1125** [comment]
perdon agrega la el redirect despues de esta linea https://github.com/culqi/culqi-woocommerce/blob/master/culqi-woocommerce.php#L486

**Comment by kasbsquall** [comment]
Buenas, pongo  wp_redirect( 'http://www.mysite.com/new-page/', 301 );
exit;

carga la venta y no pasa nada, que estoy haciendo mal

**Comment by LizRuelas** [comment]
Hola @kasbsquall  por favor escríbenos a integrate@culqi.com para brindarte el soporte necesario.

Saludos

**Comment by kasbsquall** [comment]
@LizRuelas  gracias, les acabo de enviar un mensaje a ese correo.

**Comment by LizRuelas** [comment]
Hola @kasbsquall ya respondimos tu correo.
Te dejo estos enlaces como referencia:
https://stackoverflow.com/questions/503093/how-to-redirect-to-another-webpage
https://www.w3schools.com/js/js_window_location.asp
https://developer.mozilla.org/en-US/docs/Web/API/Window/location

Saludos

**Comment by kasbsquall** [comment]
Buenas, doy por solucionado el tema.
Se logró hacer el direccionamiento usando 
https://www.w3schools.com/js/js_window_location.asp

En la línea: https://github.com/culqi/culqi-woocommerce/blob/master/culqi-woocommerce.php#L486
Muchas gracias.

**Comment by TregRek** [comment]
Buenas una consulta alguien sabe como resolver este mismo problema pero en el plugin que se saco para el 2019 (el que tiene para pago efectivo)? estoy comparando pero el function ha cambiado :/
