### ISSUE TITLE
Actualización para Pago Efectivo

### ISSUE THREAD

**Issue by feddu** [culqi/culqi-woocommerce#38]
Hola quería saber si tienen una fecha aproximada para usar pago efectivo? o no es necesaria?

**Comment by brayancruces** [comment]
Hola @feddu , en esta semana se va ir actualizando el plugin con esa nueva funcionalidad. :)

**Comment by poliverach** [comment]
Hola, para cuando tiene programado la actualización del plugin de woo?

**Comment by brayancruces** [comment]
¡Hola a todos! 

Ya se encuentra una rama donde esta versiòn actualizada con PagoEfectivo e instalar en sus sitios. 

La pueden descargar de aquì: https://github.com/culqi/culqi-woocommerce/tree/feature/multipayment

**Comment by angelgrimaldo** [comment]
@brayancruces buen día, por favor confirmar sí ya hay una versión estable con esta actualización. 

Muchas gracias.

**Comment by poliverach** [comment]
Aye estuve haciendo pruebas y el aun tiene fallas, o no se conectaba o cuando se conectaba seleccionaba un banco la peticion en background retornaba un 404. Ojalá salgan del Beta pronto.
