### ISSUE TITLE
Pago Efectivo

### ISSUE THREAD

**Issue by IdUserNotFound** [culqi/culqi-woocommerce#39]
Hola, ¿para cuando tienen planeado actualizar el plugin con la opción de Pago Efectivo?

**Comment by IdUserNotFound** [comment]
> ¡Hola @IdUserNotFound! , publicamos el plugin actualizado en la siguiente rama
> 
> https://github.com/culqi/culqi-woocommerce/tree/feature/multipayment
> 
> Puedes bajartelo de ahi y actualizar tu plugin.

Muchas gracias! Una sola consulta: ya acomode el objeto culqi.settings para que aparezca: "Pedido # (y el numero de pedido)" en vez de la descripción pero lo que no se es como hacer que vuelva a salir la imagen de mi comercio como en la versión anterior.

**Comment by brayancruces** [comment]
En el siguiente commit  del plugin se añadirá la posibilidad de modificar el logo desde el Admin.  Una vez lo publique tendrias que editar la descripcion nuevamente a lo que cambiaste :smile:

**Comment by brayancruces** [comment]
¡Hola @IdUserNotFound ! 

Te escribo nuevamente para saber si has tenido algun inconveniente adicional con el plugin, Por favor, me comentas :)

**Comment by IdUserNotFound** [comment]
Hola! hasta ahora todo bien, solo necesito poner la imagen de mi comercio en el checkout y no he revisado si ya se puede porque he andado full. Gracias por escribir!
________________________________

**Comment by angelgrimaldo** [comment]
@brayancruces  consulta rápida. En la configuración, en la parte donde dice  URL de webhook. Esa URL donde debo colocarla y cómo colocarla en el panel de CULQI?

**Comment by brayancruces** [comment]
Hola @angelgrimaldo, 

Debes entrar a tu panel de Culqi, en la seccion Desarrollo > Webhooks.  Ahi debes añadir un webhook de tipo order.status.change, colocas esa URL y guardas cambios.

**Comment by angelgrimaldo** [comment]
@brayancruces cuando ingreso el webhooks en el panel de Culqi, me aparece así:

![image](https://user-images.githubusercontent.com/6952728/49768167-7a84db80-fca9-11e8-82bf-5e52f35b4e70.png)

Es decir, en wordpress me indica   index.php?wc-api=cq_webhook   pero cuando lo ingreso a CULQI el guió medio que va entre wc-api no se visualiza. ¿Es normal?

**Comment by jchavezg** [comment]
A mi sí se me ve y he realizado el testeo correspondiente y funciona perfecto!
![image](https://user-images.githubusercontent.com/27743126/52921057-0ab25300-32e1-11e9-8383-96506190373a.png)

**Comment by angelgrimaldo** [comment]
@brayancruces  no me esta actualizando el estado del pedido cuando una venta es exitosa. ¿Se tiene que configurar algun webhook desde woocommerce?

![image](https://user-images.githubusercontent.com/6952728/54062958-65034d00-41d7-11e9-8b65-98df73dac11c.png)

**Comment by angelgrimaldo** [comment]
¿Hiciste alguna configuración en el Webhooks por el lado de Wordpress


*--------------------------------------------*

*Ángel Grimaldo Martínez B*.
*www.angelgrimaldo.com <http://www.angelgrimaldo.com/>*
*Teléfono:* (511) 936389191
*LinkedIn:* *www.linkedin.com/in/angelgrimaldo
<http://www.linkedin.com/in/angelgrimaldo>*

[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Remitente
notificado con
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
08/04/19
8:39:17 a. m.

**Comment by jchavezg** [comment]
No, solo en la pestaña de eventos en culqi

**Comment by angelgrimaldo** [comment]
Sigo sin que se me actualice el estado a Pagado, solo llego a Procesando... ¿el webhook lo colocan con autentificación o no?

Quedo muy atento.

**Comment by gonzalesc** [comment]
Hay algún truco acerca de esto? a mi tampoco me funciona la verdad. Cree en webhook en el dash de Culqi y éste siempre me da error 404 como si la URL no existiese pero he validado 1000 veces que la URL es la correcta.

Le envié correo a Culqi pero sé que tardará 1 mes en eso, para responderme que verifique bien la URL, por eso pregunto por aqui si alguien tuvo este mismo inconveniente.

Saludos

**Comment by fingerbass** [comment]
Hola:

Yo he logrado hacer las pruebas satisfactorias. El Webhook solo aplica cuando habilitan multipagos, para ser más preciso, cuando el usuario no usa tarjeta de débito/crédito y usan PagoEfectivo o similares.

Cabe resaltar que toda la información la he obtenido de Culqi y he usado una herramienta para servicios web; en mi caso, postman.

1. Instalación y configuración de plugin para Woocommerce (https://github.com/culqi/culqi-woocommerce)
 En la configuracón deben activar la casilla *Habilitar multipagos* y copiar la URL del webhook
![image](https://user-images.githubusercontent.com/22179396/66020608-37e8f580-e4ad-11e9-89f4-60559cdc5aa1.png)

2. Desde el panel de Culqi ingresa a *Eventos* > *Webhooks* y debes registrar el evento *order.status.changed*. Pegar la URL copiada en el punto 1. Más información en: https://www.culqi.com/docs/#/multipagos/eventos
![image](https://user-images.githubusercontent.com/22179396/66020724-afb72000-e4ad-11e9-8cc4-a32e857f9a01.png)

3. Generen una orden de pago desde su web y elijan efectivo.
![image](https://user-images.githubusercontent.com/22179396/66020904-5bf90680-e4ae-11e9-8586-4de361abd310.png)
![image](https://user-images.githubusercontent.com/22179396/66020911-60252400-e4ae-11e9-981b-095e6ec2dec1.png)

4. Hasta aquí podríamos decir que ya está OK, pero si quieres realizar pruebas, debes seguir las indicaciones de esta sección *Testeando Recepción de Eventos* https://www.culqi.com/docs/#/multipagos/pruebas. Se van al link de ejemplo cuando la orden es pagada y deben copiarlo en postman. Modifiquen según su orden de pago. Hacen el envío y deberían recibir en el resultado el mensaje success. El pedido en su woocommerce debería cambiar de EN ESPERA a PROCESANDO.
*Nota*: Las fechas estan en formato UNIX
![image](https://user-images.githubusercontent.com/22179396/66021216-80091780-e4af-11e9-9149-93056b499f68.png)

![image](https://user-images.githubusercontent.com/22179396/66021132-27397f00-e4af-11e9-9f0b-85db3a8fadbd.png)

![image](https://user-images.githubusercontent.com/22179396/66021247-97e09b80-e4af-11e9-8668-57d33b8cf19a.png)

Espero sirva de ayuda. Por otro lado, si alguien ha logrado personalizar el logo se agradece compartir  la solución aplicada.

**Comment by angelgrimaldo** [comment]
Claro, sí cambia de estado, pero el estado solo cambia hasta el estado
"Procesando". Es decir, nunca cambia a "Completado", aún cuando el pedido
ha sido pagado.

En MercadoPago el cambio de estado funciona perfectamente. Cambia a
Completado cuando el pedido ha sido pagado, sea con Tarjeta o con
PagoEfectivo.

¿A alguien le llega a cambiara al estado "Completado" cuando se hace
efectivo el pago?



*--------------------------------------------*

*Ángel Grimaldo Martínez B*.
*www.angelgrimaldo.com <http://www.angelgrimaldo.com/>*
*Teléfono:* (511) 936389191
*LinkedIn:* *www.linkedin.com/in/angelgrimaldo
<http://www.linkedin.com/in/angelgrimaldo>*

**Comment by jchavezg** [comment]
El estado completado solo lo cambias tu manualmente para PAGOEFECTIVO.

Para las tarjetas funciona perfectamente.




ᐧ

**Comment by fingerbass** [comment]
En mi caso, sea un pago con tarjeta o pagoefectivo siempre actualiza a **PROCESANDO**, el cambio a **COMPLETADO** lo hago manual.

Es mi primera vez con Woocommerce y aún me estoy documentando; sin embargo, estoy considerando agregar un endpoint o editar el existente para que en lugar de cambiar a PROCESANDO se actualice a COMPLETADO, creo que optaré por esto último. @jchavezg, cuando indicas que para las tarjetas funciona perfectamente ¿Te refieres a que el estado se cambio a **COMPLETADO**?

**Comment by jchavezg** [comment]
Así es. Cambia automático en tarjetas.

Saludos cordiales,

ᐧ
