### ISSUE TITLE
Error "undefined" en woocommerce 

### ISSUE THREAD

**Issue by M4NU31** [culqi/culqi-woocommerce#41]
Buen día, cuando intento realizar algún pago a traves del plugin de woocommerce, aparece la ventana para ingresar los datos de la tarjeta, sin embargo, cuando son rellenados y se procede a realizar el pago, aparece un mensaje en letras rojas que dice "undefined"

**Comment by chamblues** [comment]
A mi también me sucede el mismo problema de "undefined" , envié un correo a soporte@culqi.com y a integrate@culqi.com, espero puedan ayudarnos con esto.

Saludos.

**Comment by brayancruces** [comment]
Hola, @M4NU31 
¿En qué ambiente realizaste las pruebas?   🤔

**Comment by M4NU31** [comment]
lo hice en la pag de mi proyecto con una tarjeta real, pero el personal de culqi ya me contestó, al parecer el problema venia por parte de ellos, ya que automaticamente al recibir el correo ya podía realizar las transacciones
