### ISSUE TITLE
Ayer me di de alta en Culqi - Woocommerce pero no funciona

### ISSUE THREAD

**Issue by mmacedoz** [culqi/culqi-woocommerce#42]
Hoy actualicé las keys (pública y privada) pero no funciona 
tengo woocommerce 3.5.5
wordpress 5.0.3
theme: Zerif Lite

**Comment by gonzalesc** [comment]
En que sentido no funciona, tenes algún mensaje de error? tu console log que dice?

**Comment by mmacedoz** [comment]
Hola Alexander, muchas gracias por responder, ayer recibí la comunicación
de culqi, pues les escribí avisando del tema, lo que pasó es que uno
generaba el pedido y al darle pagar, salía el cuadro de diálogo de culqi,
uno ingresaba los datos y no procesaba el pago....simplemente no procesaba
nada de nada, pero entiendo que han debido estar viendo el tema porque
ahora ya está corregido.
Muy agradecido Alexander por tu comunicación
