### ISSUE TITLE
Whitelabel Error Page

### ISSUE THREAD

**Issue by mingogs** [culqi/culqi-woocommerce#43]
Hola, desde esta madrugada estoy recibiendo este mensaje luego de dar click en "pagar" para finalizar cualquier compra:

```
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.
Fri Mar 22 01:57:08 PET 2019
There was an unexpected error (type=Internal Server Error, status=500).
500 null
```

Pensé que podía ser un tema de llaves, las actualicé en el dashboard de Culqi y en el WooCommerce de mi web, pero nada.

¿Alguien sabe cómo se puede solucionar eso?

Web: gladiadores.vip/entradas
Versión de WordPress: 5.1.1
versión de woocommerce 3.5.7
Versión de Plugin de Culqi: 2.1.1

**Comment by LinuxEvangelist** [comment]
Tengo el mismo error en el ambiente de pruebas cuando le paso las tarjetas de prueba. 
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Sun Mar 24 00:45:38 UTC 2019
There was an unexpected error (type=Method Not Allowed, status=405).
Request method 'GET' not supported

**Comment by mingogs** [comment]
> Tengo el mismo error en el ambiente de pruebas cuando le paso las tarjetas de prueba.
> Whitelabel Error Page
> This application has no explicit mapping for /error, so you are seeing this as a fallback.
> 
> Sun Mar 24 00:45:38 UTC 2019
> There was an unexpected error (type=Method Not Allowed, status=405).
> Request method 'GET' not supported
