### ISSUE TITLE
Currency code no se envía en request

### ISSUE THREAD

**Issue by kenramirez12** [culqi/culqi-woocommerce#46]
Buenas tardes,
por alguna razón al realizar el checkout no se envía el código de moneda en el request y me da el siguiente mensaje: `Hubo algunos problemas al intentar validar tu compra. Contáctanos para ayudarte.`

En el log de culqi me sale lo siguiente:
```
{
  "object": "error",
  "type": "parameter_error",
  "merchant_message": "El campo 'currency_code' es inválido o está vacío, el código de la moneda en tres letras (Formato ISO 4217). Culqi actualmente soporta las siguientes monedas: 'USD', PEN'.",
  "user_message": "Hubo algunos problemas al intentar validar tu compra. Contáctanos para ayudarte.",
  "param": "currency_code"
}
```

El request es este:
```
{
  "mail": "kenramirezp@gmail.com",
  "brand": "Visa",
  "card_number": "411111******1111"
}
```

He probado cambiando la moneda a dólares americanos pero el problema persiste. Alguna idea?

**Comment by LizRuelas** [comment]
Hola Karen 

El error que tienes se debe a la configuración de tu comercio, la cuál puede ser solucionada únicamente por parte de Culqi.

Por favor, escríbenos a culqi.com/soporte y proporciona tu llave publica para que puedan terminar de configurarlo y de esa forma ya no tengas problemas.

Saludos

**Comment by kenramirez12** [comment]
> Hola Karen
> 
> El error que tienes se debe a la configuración de tu comercio, la cuál puede ser solucionada únicamente por parte de Culqi.
> 
> Por favor, escríbenos a culqi.com/soporte y proporciona tu llave publica para que puedan terminar de configurarlo y de esa forma ya no tengas problemas.
> 
> Saludos

Gracias, la haré ahora.

**Comment by dnavarro174** [comment]
Buenos días, yo me contacte hace 5 días y no me responden. Help me!!!

**Comment by LizRuelas** [comment]
@dnavarro174 los developers de aqui no podemos ayudarte, los unicos que pueden solucionarte el problema son los de Culqi por que son los unicos que pueden configurar tu comercio al interno :/
